debug: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true
    name: boot
    username: root
    password: abcd
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.admin.pojo
  mapper-locations: classpath:mapper/*/*.xml

